@startuml


skinparam activity {
  BarColor Black 
  BackgroundColor White
  BorderColor Black
}


(*) --> "Using MAUT create partial configuration based on preferences"
--> validate and repair configuration
--> "save in db"

if "has better configruation in db" then
    -->"use best in db"
     --> (*)
else
    --> "use generated"
     --> (*)
endif
   
@enduml